### ISSUE TITLE
Feature request , send range as multiline 

### ISSUE THREAD

**Issue by ArbitRandomUser** [Klafyvel/REPLSmuggler.jl#28]
I used vim-slime initially a lot , i tried  julia-repl-vim (https://github.com/andreypopp/julia-repl-vim ) and what i really liked about
julia-repl-vim is that when i sent a range of lines , it isnt executed line by line but as a multiline statement in the repl. This is nice because if there is an error in line 3 of the 5 lines that you send to the repl you dont want lines 4 and 5 to execute.

would be nice if this behaviour (could be optional config) was available in REPLSmuggler
 too

example:
![fig](https://github.com/user-attachments/assets/a44ee781-f323-42a3-9f2a-ef301256212a)

**Comment by Klafyvel** [comment]
Hi! Thank you for your interest. This is indeed a nice feature to add. I'll
do it eventually, but if you're interested in contributing this can be done
by tweaking the JuliaSyntax call in eval.jl. You'd also need to adapt a bit
the protocol to add a flag that tells the server to evaluate all at once
and increment the protocol version number accordingly, I'm not sure if that
qualifies as a breaking change. On the neovim plugin's side you could
probably simply add a configuration flag to tell it to use the new protocol
flag or not.

**Comment by fredrikekre** [comment]
I think this could be fixed by using [Bracketed paste mode](https://en.wikipedia.org/wiki/Bracketed-paste#Description_of_bracketed-paste). I think that would also fix the first point here: https://discourse.julialang.org/t/ann-replsmuggler-jl-send-code-to-your-julia-repl-and-get-neo-vim-diagnostics-in-return/111420/2 since the Julia REPL would fix the indentation when seeing code being pasted (I think).

**Comment by Klafyvel** [comment]
Hi Fredrikekre, do you mean sending the escape code for bracketed paste mode, writing the text, and then sending enter? It might be an option, but how do you catch exceptions then? ArbitRandomUser showed me another way to input the text to the REPL in #29 that will also solve the issue you mentioned on discourse. Maybe you can give it a try to see if it works for you?

**Comment by fredrikekre** [comment]
Hmm, not sure then. What are you catching exceptions for?

**Comment by Klafyvel** [comment]
They are sent back to neovim to display diagnostics exactly like the LSP would do.

**Comment by fredrikekre** [comment]
Ah okay, I thought you had to `smuggle(err)` explicitly. Did this change or am I misremembering how things worked?

**Comment by Klafyvel** [comment]
Nop, I think errors were smuggled back from the beginning. Maybe you are
referring to the ability to explicitly smuggling back diagnostics (for
example JET's) that was added recently.
