### ISSUE TITLE
Feature request, Send only selection

### ISSUE THREAD

**Issue by ArbitRandomUser** [Klafyvel/REPLSmuggler.jl#37]
right now a selection send the all the lines that span the selection ,
while debugging sometimes you want to just execute a part of the line

`somebigfunc( func1(arg1,arg2) , func2(1,2,3,4) , func3() )`

sometimes you just want to select `func2(1,2,3,4)` and send to the repl.

copying it , putting it on a line and sending it is one option, but is not ergonomic.

**Comment by Klafyvel** [comment]
Yes, that's something I'd like to fix. If I remember correctly vim-slime
does it correctly, which means I failed to adapt the code from there. :)
It's a matter of handling correctly the visual selection (character vs line
vs block mode).

**Comment by Klafyvel** [comment]
Fixed in https://github.com/Klafyvel/nvim-smuggler/pull/16.
