### ISSUE TITLE
Protocol Exception Error

### ISSUE THREAD

**Issue by ArbitRandomUser** [Klafyvel/REPLSmuggler.jl#38]
```
julia> 
┌ Info: New client connected
└   session = Session{Base.PipeEndpoint}()

┌ Error: REPLSmuggler.Protocols.ProtocolException(0x00000000, "Invalid method `configure` with 1 parameters.")
└ @ REPLSmuggler.Server ~/.julia/packages/REPLSmuggler/53cwk/src/Server.jl:166
```

perhaps new protocol warrants a version bump ?

the tagged version that Pkg installs is not compatible with `main` on nvim-smuggler which is what most nvim plugin managers will use by default.

For anyone running into this error right now use the `main` branch with Pkg

`(@v1.10) pkg> add REPLSmuggler#main`

**Comment by Klafyvel** [comment]
Wild people are running around without pinning their Vim plugins :p I'll bump the version.
